<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Testcontainers.Redis"/>
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Libraries\UrlShortener.Libraries.Testing\UrlShortener.Libraries.Testing.csproj"/>
        <ProjectReference Include="..\..\src\UrlShortener.RedirectApi\UrlShortener.RedirectApi.csproj"/>
    </ItemGroup>

</Project>